version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    ports:
      - "5173:5173"
    volumes:
      - ./:/var/www
    depends_on:
      - db    

  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8976:80"
    container_name: pizzaapi
    depends_on:
      - app

  db:
    image: mysql:latest
    container_name: laravel_db
    restart: always
    environment:
      MYSQL_DATABASE: anz_store
      MYSQL_ROOT_PASSWORD: 12345678
